import { Info } from "lucide-react";

export function AiDisclaimer() {
  return (
    <div className="mt-4 flex items-start gap-2 rounded-md border border-border bg-muted/50 px-3 py-2 text-xs text-muted-foreground">
      <Info className="mt-0.5 h-3.5 w-3.5 shrink-0" />
      <p>
        <span className="font-medium text-foreground">AI Disclaimer:</span> This content was
        generated by artificial intelligence and should be reviewed before use. Verify critical
        information, deadlines, legal matters, and business decisions.
      </p>
    </div>
  );
}
